// ── Application Route Constants ────────────────────────

export const ROUTES = {
  // Public
  HOME: "/",
  CATEGORIES: "/categories",
  CATEGORY_DETAIL: (slug: string) => `/categories/${slug}`,
  BRANDS: "/brands",
  BRAND_DETAIL: (slug: string) => `/brands/${slug}`,
  PRODUCTS: "/products",
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  FLASH_DEALS: "/flash-deals",
  DEALS: "/deals",
  ABOUT: "/about",
  CONTACT: "/contact",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS: "/terms-and-conditions",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  TRACK_ORDER: "/track-order",
  TRACKING: "/track-order",
  WISHLIST: "/wishlist",
  ACCOUNT: "/account",

  // Auth
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  // Protected
  DASHBOARD: "/dashboard",
  CLIENTS: "/clients",
  PAYMENTS: "/payments",
  REPORTS: "/dashboard/reports",
  REPORTS_PROFIT: "/dashboard/reports/profit",
  REPORTS_STOCK: "/dashboard/reports/stock",
  REPORTS_LOW_STOCK: "/dashboard/reports/low-stock",
  REPORTS_TRANSACTIONS: "/dashboard/reports/transactions",
  REPORTS_SALES: "/dashboard/reports/sales",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/account",
  ADMIN_PROFILE: "/dashboard/profile",
  ADMIN_CARTS: "/dashboard/carts",
  ADMIN_ORDER_CREATE: "/dashboard/orders/create",
  ADMIN_WISHLISTS: "/dashboard/wishlists",
  ACCOUNT_HUB: "/account",
  SETTINGS: "/settings",
  REVIEWS: "/dashboard/reviews",
  ACTIVITY: "/dashboard/activity",
  ADMIN_INVENTORY: "/dashboard/inventory",
  ADMIN_INVENTORY_AUDIT: "/dashboard/inventory/audit",
  CUSTOMERS: "/dashboard/customers",
  ADMIN_FLASH_DEALS: "/dashboard/flashdeal",
} as const;

export const PUBLIC_ROUTES = [
  ROUTES.HOME,
  ROUTES.CATEGORIES,
  ROUTES.BRANDS,
  ROUTES.PRODUCTS,
  ROUTES.FLASH_DEALS,
  ROUTES.DEALS,
  ROUTES.ABOUT,
  ROUTES.CONTACT,
  ROUTES.PRIVACY_POLICY,
  ROUTES.TERMS,
  ROUTES.CART,
  ROUTES.CHECKOUT,
  ROUTES.CHECKOUT_SUCCESS,
  ROUTES.TRACK_ORDER,
  ROUTES.WISHLIST,
] as const;

export const AUTH_ROUTES = [
  ROUTES.LOGIN,
  ROUTES.REGISTER,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.RESET_PASSWORD,
] as const;

export const PROTECTED_ROUTES = [
  ROUTES.DASHBOARD,
  ROUTES.CLIENTS,
  ROUTES.PAYMENTS,
  ROUTES.REPORTS,
  ROUTES.NOTIFICATIONS,
  ROUTES.PROFILE,
  ROUTES.ACCOUNT_HUB,
  ROUTES.SETTINGS,
  ROUTES.ADMIN_CARTS,
  ROUTES.ADMIN_INVENTORY,
  ROUTES.ADMIN_INVENTORY_AUDIT,
  ROUTES.CUSTOMERS,
  ROUTES.ADMIN_FLASH_DEALS,
] as const;
